export interface LanSettings {
  enabled: boolean;
  port: number;
  username: string;
  password: string;
}

export interface LanStatus {
  running: boolean;
  address?: string;
  open: boolean;
}

export class LanSharingCoordinator {
  public static splitSections(text: string): { block: string; direct: string } {
    let block = "";
    let direct = "";
    let current: "block" | "direct" | null = null;

    for (const rawLine of text.split(/\r?\n/)) {
      const trimmed = rawLine.trim();
      if (!trimmed || trimmed.startsWith("#")) {
        continue;
      }
      const lowered = trimmed.toLowerCase();
      if (lowered === "[block]") {
        current = "block";
        continue;
      }
      if (lowered === "[direct]") {
        current = "direct";
        continue;
      }
      if (lowered.startsWith("[")) {
        current = null;
        continue;
      }
      if (current === "block") {
        block += trimmed + "\n";
      } else if (current === "direct") {
        direct += trimmed + "\n";
      }
    }

    return { block, direct };
  }

  public static normalizeMihomoDomains(domains: string): string[] {
    return domains
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line.length > 0 && !line.startsWith("#"))
      .map((line) => (line.startsWith("+.") ? line.slice(2) : line));
  }

  public static compileCombinedRuleset(
    userRoutes: string | null,
    bundledDomains: string,
    bundledIps: string
  ): string {
    const { block: userBlock, direct: userDirect } = userRoutes
      ? this.splitSections(userRoutes)
      : { block: "", direct: "" };

    const normalizedDomains = this.normalizeMihomoDomains(bundledDomains).join("\n");
    let out = "# Generated by LumiNet Control UI\n";
    out += "[block]\n";
    if (userBlock) {
      out += userBlock;
    }
    out += "[direct]\n";
    if (normalizedDomains) {
      out += normalizedDomains + "\n";
    }
    if (bundledIps.trim()) {
      out += bundledIps.trim() + "\n";
    }
    if (userDirect) {
      out += userDirect;
    }
    return out;
  }

  public static unusableBehindTunnel(kind: string, carriesQuic: boolean): string | null {
    if (carriesQuic) return null;
    const k = kind.toLowerCase();
    if (k === "hysteria" || k === "hysteria2" || k === "tuic") {
      return `${kind} operates over UDP/QUIC requiring datagrams >= 1280 bytes which exceed standard MASQUE inner MTU`;
    }
    return null;
  }

  public static isOpenAuth(settings: LanSettings): boolean {
    return !settings.username.trim() || !settings.password.trim();
  }
}
