export class PrivoxyActionGenerator {
  private forwardDomains: Set<string> = new Set();
  private bypassDomains: Set<string> = new Set();
  public socks5Proxy: string;
  constructor(socks5Proxy: string) {
    this.socks5Proxy = socks5Proxy;
  }

  addForwardDomain(domain: string): void {
    const clean = domain.trim().replace(/\.$/, '').toLowerCase();
    if (clean) this.forwardDomains.add(clean);
  }

  addDirectBypass(domain: string): void {
    const clean = domain.trim().replace(/\.$/, '').toLowerCase();
    if (clean) this.bypassDomains.add(clean);
  }

  generateActionFile(): string {
    const lines: string[] = [];
    lines.push('# Generated by LumiNet PrivoxyActionGenerator');
    lines.push('{-forward-override}');
    for (const d of Array.from(this.bypassDomains).sort()) {
      lines.push(`.${d}`);
    }
    lines.push('');
    lines.push(`{+forward-override{forward-socks5 ${this.socks5Proxy} .}}`);
    for (const d of Array.from(this.forwardDomains).sort()) {
      lines.push(`.${d}`);
    }
    return lines.join('\n');
  }
}
