package proxy

import (
	"crypto/rand"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"regexp"
	"strconv"
	"strings"
	"time"
)

// parseCPSPacket parses Custom Protocol Signature format tags.
// Supported tags:
// - <b 0c0d>: hex bytes
// - <t>: 32-bit big-endian timestamp
// - <c>: 32-bit big-endian counter
// - <r 10>: 10 random bytes
// - <n>: 64-bit big-endian nonce
// - <x 5>: XOR key for the preceding generated bytes
func parseCPSPacket(cps string) ([]byte, error) {
	if cps == "" {
		return nil, nil
	}

	var result []byte

	tagRegex := regexp.MustCompile(`<([btcrnx])\s*([^>]*)>`)
	matches := tagRegex.FindAllStringSubmatch(cps, -1)

	for _, match := range matches {
		if len(match) < 3 {
			continue
		}

		tagType := match[1]
		tagData := strings.TrimSpace(match[2])

		switch tagType {
		case "b": // Static bytes (hex)
			if tagData != "" {
				tagData = strings.TrimPrefix(tagData, "0x")
				tagData = strings.TrimPrefix(tagData, "0X")
				tagData = strings.ReplaceAll(tagData, " ", "")
				bytes, err := hex.DecodeString(tagData)
				if err != nil {
					return nil, fmt.Errorf("invalid hex in <b>: %w", err)
				}
				result = append(result, bytes...)
			}

		case "c": // Counter (32-bit)
			counter := uint32(time.Now().Unix() % 0xFFFFFFFF)
			buf := make([]byte, 4)
			binary.BigEndian.PutUint32(buf, counter)
			result = append(result, buf...)

		case "t": // Timestamp (32-bit)
			timestamp := uint32(time.Now().Unix())
			buf := make([]byte, 4)
			binary.BigEndian.PutUint32(buf, timestamp)
			result = append(result, buf...)

		case "r": // Random bytes
			length := 0
			if tagData != "" {
				length, _ = strconv.Atoi(tagData)
				if length > 1000 {
					length = 1000
				}
			}
			if length > 0 {
				randomBytes := make([]byte, length)
				_, err := rand.Read(randomBytes)
				if err != nil {
					return nil, err
				}
				result = append(result, randomBytes...)
			}

		case "n": // Nonce (64-bit)
			nonce := uint64(time.Now().UnixNano())
			buf := make([]byte, 8)
			binary.BigEndian.PutUint64(buf, nonce)
			result = append(result, buf...)

		case "x": // XOR key (for simple obfuscation of the current packet content)
			if tagData != "" {
				key, _ := strconv.Atoi(tagData)
				if len(result) > 0 {
					for i := range result {
						result[i] ^= byte(key)
					}
				}
			}
		}
	}

	return result, nil
}
