package com.luminet.android.tunnel

/**
 * Settings for local network proxy sharing (dual HTTP & SOCKS5).
 */
data class LanShareSettings(
    val enabled: Boolean = false,
    val port: Int = 1080,
    val username: String = "",
    val password: String = ""
) {
    val isOpen: Boolean
        get() = username.isBlank() || password.isBlank()
}

/**
 * Live status of the LAN sharing listener.
 */
data class LanShareStatus(
    val running: Boolean = false,
    val address: String? = null,
    val open: Boolean = false
)

/**
 * Coordinates route ruleset compilation, mihomo domain normalization,
 * and LAN proxy sharing on Android.
 */
object LanShareCoordinator {

    fun splitSections(text: String): Pair<String, String> {
        val block = StringBuilder()
        val direct = StringBuilder()
        var current: StringBuilder? = null

        for (rawLine in text.lines()) {
            val trimmed = rawLine.trim()
            if (trimmed.isEmpty() || trimmed.startsWith("#")) {
                continue
            }
            val lowered = trimmed.lowercase()
            when {
                lowered == "[block]" -> current = block
                lowered == "[direct]" -> current = direct
                lowered.startsWith("[") -> current = null // Unknown section, fail-closed
                current != null -> {
                    current.append(trimmed).append("\n")
                }
            }
        }
        return Pair(block.toString(), direct.toString())
    }

    fun normalizeMihomoDomains(domains: String): List<String> {
        return domains.lines()
            .map { it.trim() }
            .filter { it.isNotEmpty() && !it.startsWith("#") }
            .map { if (it.startsWith("+.")) it.removePrefix("+.") else it }
    }

    fun compileCombinedRuleset(
        userRoutes: String?,
        bundledDomains: String,
        bundledIps: String
    ): String {
        val (userBlock, userDirect) = if (userRoutes != null) {
            splitSections(userRoutes)
        } else {
            Pair("", "")
        }

        val normalized = normalizeMihomoDomains(bundledDomains).joinToString("\n")
        val sb = StringBuilder()
        sb.append("# Generated by LumiNet Mobile Engine\n")
        sb.append("[block]\n")
        if (userBlock.isNotEmpty()) {
            sb.append(userBlock)
        }
        sb.append("[direct]\n")
        if (normalized.isNotEmpty()) {
            sb.append(normalized).append("\n")
        }
        if (bundledIps.isNotBlank()) {
            sb.append(bundledIps.trim()).append("\n")
        }
        if (userDirect.isNotEmpty()) {
            sb.append(userDirect)
        }
        return sb.toString()
    }

    fun unusableBehindTunnel(kind: String, carriesQuic: Boolean): String? {
        if (carriesQuic) return null
        return when (kind.lowercase()) {
            "hysteria", "hysteria2", "tuic" ->
                "$kind runs over UDP/QUIC requiring datagrams >= 1280 bytes which exceed standard MASQUE inner MTU"
            else -> null
        }
    }
}
