package com.luminet.android.tunnel

import java.util.TreeSet

class PrivoxyActionGenerator(
    val socks5Proxy: String
) {
    private val forwardDomains = TreeSet<String>()
    private val bypassDomains = TreeSet<String>()

    fun addForwardDomain(domain: String) {
        val clean = domain.trim().trimEnd('.').lowercase()
        if (clean.isNotEmpty()) forwardDomains.add(clean)
    }

    fun addDirectBypass(domain: String) {
        val clean = domain.trim().trimEnd('.').lowercase()
        if (clean.isNotEmpty()) bypassDomains.add(clean)
    }

    fun generateActionFile(): String {
        val sb = StringBuilder()
        sb.append("# Generated by LumiNet PrivoxyActionGenerator\n")
        sb.append("{-forward-override}\n")
        for (d in bypassDomains) {
            sb.append(".$d\n")
        }
        sb.append("\n")
        sb.append("{+forward-override{forward-socks5 $socks5Proxy .}}\n")
        for (d in forwardDomains) {
            sb.append(".$d\n")
        }
        return sb.toString()
    }
}
